# Generated by Django 4.0.6 on 2023-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collabid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
