# Generated by Django 4.0.6 on 2023-03-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_alter_user_collabid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collabid',
        ),
    ]
