# Generated by Django 4.0.6 on 2023-03-20 05:55

from django.db import migrations, models
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='lastname',
            field=models.CharField(default=userAuth.models.foo, max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='status',
            field=models.CharField(default=userAuth.models.foofoo, max_length=10),
        ),
    ]
