# Generated by Django 4.0.6 on 2023-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_alter_mentor_lastname_alter_mentor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
