# Generated by Django 4.0.6 on 2023-03-20 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_alter_mentor_lastname_alter_mentor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
