# Generated by Django 4.0.6 on 2023-03-20 07:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0007_alter_mentor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentorid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('internid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='NA', max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('college', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=10)),
                ('doj', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('mentorid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userAuth.mentor')),
            ],
            options={
                'db_table': 'intern',
            },
        ),
    ]
