# Generated by Django 4.0.6 on 2023-03-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0008_remove_mentor_id_alter_mentor_mentorid_intern'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='intern',
            table='interns',
        ),
    ]
