# Generated by Django 4.0.6 on 2023-03-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_task_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userAuth.mentor'),
        ),
    ]
